apiVersion: v1 

kind: Service 

metadata: 

  name: kubernetes-rails-load-balancer 

  labels: 

    name: kubernetes-rails-load-balancer 

spec: 

  ports: 

    - nodePort: 30163  

      port: 8080       

      targetPort: 3030   

      protocol: TCP 

  selector:            

    app: rails-app 

  type: NodePort 

  

 

 apiVersion: apps/v1   

  

kind: Deployment   

  

metadata:   

  

   name: kubernetes-rails-deployment   

  

spec:   

  

  replicas: 4   

  

  selector:   

  

    matchLabels:   

  

      app: rails-app   

  

  template:  

  

    metadata:   

  

      labels:   

  

        app: rails-app   

  

spec:   

  

  containers:   

  

  - name: rails-app   

  

    image: subhcse/kubernetes-rails:latest   

  

    ports:   

  

    - containerPort: 3000  

  

imagePullSecrets:   

  

    - name: my-docker-secret 

 

apiVersion: v1 

kind: ConfigMap 

metadata: 

  name: env 

data: 

  RAILS_ENV: production 

  RAILS_LOG_TO_STDOUT: enabled 

  RAILS_SERVE_STATIC_FILES: enabled 

  DATABASE_URL: http://localhost:30163 

  CASSANDRA_SEEDS: cassandra://cassandra-0.cassandra.default.svc.cluster.local:9042/ 

  MAX_HEAP_SIZE:256M 

  HEAP_NEWSIZE:100M           

  CASSANDRA_CLUSTER_NAME:"Cassandra"             

  CASSANDRA_DC:"DC1"        - name: HEAP_NEWSIZE 

  CASSANDRA_RACK:"Rack1"          value: 100M 

  CASSANDRA_ENDPOINT_SNITCH:"GossipingPropertyFileSnitch" 

